package com.cuit.drawdream.bean;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appInfoEntityDaoConfig;

    private final AppInfoEntityDao appInfoEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appInfoEntityDaoConfig = daoConfigMap.get(AppInfoEntityDao.class).clone();
        appInfoEntityDaoConfig.initIdentityScope(type);

        appInfoEntityDao = new AppInfoEntityDao(appInfoEntityDaoConfig, this);

        registerDao(AppInfoEntity.class, appInfoEntityDao);
    }
    
    public void clear() {
        appInfoEntityDaoConfig.getIdentityScope().clear();
    }

    public AppInfoEntityDao getAppInfoEntityDao() {
        return appInfoEntityDao;
    }

}
