package com.cuit.drawdream.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NEWS_DETAIL.
 */
public class NewsDetail {

    /** Not-null value. */
    private String nede_id;
    /** Not-null value. */
    private String nede_title;
    /** Not-null value. */
    private String nede_author;
    /** Not-null value. */
    private String nede_time;
    /** Not-null value. */
    private String nede_content;
    /** Not-null value. */
    private String nede_img;

    public NewsDetail() {
    }

    public NewsDetail(String nede_id, String nede_title, String nede_author, String nede_time, String nede_content, String nede_img) {
        this.nede_id = nede_id;
        this.nede_title = nede_title;
        this.nede_author = nede_author;
        this.nede_time = nede_time;
        this.nede_content = nede_content;
        this.nede_img = nede_img;
    }

    /** Not-null value. */
    public String getNede_id() {
        return nede_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNede_id(String nede_id) {
        this.nede_id = nede_id;
    }

    /** Not-null value. */
    public String getNede_title() {
        return nede_title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNede_title(String nede_title) {
        this.nede_title = nede_title;
    }

    /** Not-null value. */
    public String getNede_author() {
        return nede_author;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNede_author(String nede_author) {
        this.nede_author = nede_author;
    }

    /** Not-null value. */
    public String getNede_time() {
        return nede_time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNede_time(String nede_time) {
        this.nede_time = nede_time;
    }

    /** Not-null value. */
    public String getNede_content() {
        return nede_content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNede_content(String nede_content) {
        this.nede_content = nede_content;
    }

    /** Not-null value. */
    public String getNede_img() {
        return nede_img;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNede_img(String nede_img) {
        this.nede_img = nede_img;
    }

}
