package com.cuit.drawdream.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REPLAY_ENTITY.
 */
public class ReplayEntity {

    /** Not-null value. */
    private String core_nede_id;
    private String core_acco_id;
    private String core_content;
    private String core_date;

    public ReplayEntity() {
    }

    public ReplayEntity(String core_nede_id, String core_acco_id, String core_content, String core_date) {
        this.core_nede_id = core_nede_id;
        this.core_acco_id = core_acco_id;
        this.core_content = core_content;
        this.core_date = core_date;
    }

    /** Not-null value. */
    public String getCore_nede_id() {
        return core_nede_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCore_nede_id(String core_nede_id) {
        this.core_nede_id = core_nede_id;
    }

    public String getCore_acco_id() {
        return core_acco_id;
    }

    public void setCore_acco_id(String core_acco_id) {
        this.core_acco_id = core_acco_id;
    }

    public String getCore_content() {
        return core_content;
    }

    public void setCore_content(String core_content) {
        this.core_content = core_content;
    }

    public String getCore_date() {
        return core_date;
    }

    public void setCore_date(String core_date) {
        this.core_date = core_date;
    }

}
